import type { ArtifactRef } from "@autopw/run-storage";
import { RunStorage } from "@autopw/run-storage";
import { redactSecrets } from "@autopw/security";

export interface ReportCoverageRow { requirement_id: string; priority?: string; intent?: string; source?: string[]; plan_status?: string; execution_status?: string; evidence?: string; reason?: string; }
export interface ReportCaseRow { case_id: string; title?: string; requirement_refs?: string[]; origin?: { type?: string; source_ref?: string }; risk?: string; setup?: unknown[]; steps?: unknown[]; cleanup?: unknown[]; }
export function writeReport({ storage, runId, gate, auditStatus, summary, issues, resultsRef, coverage, coverageMetrics, cases, planSource, target }: { storage: RunStorage; runId: string; gate: string; auditStatus: string; summary: Record<string, unknown>; issues: Record<string, unknown>[]; resultsRef: ArtifactRef; coverage?: ReportCoverageRow[]; coverageMetrics?: Record<string, number>; cases?: ReportCaseRow[]; planSource?: string; target?: string }): { reportRef: ArtifactRef; htmlRef: ArtifactRef } {
  const safeSummary = redactSecrets(summary);
  const issueRows = issues.map((item) => `| ${escapeMarkdown(String(item.execution_id || "-"))} | ${escapeMarkdown(String(item.classification || "-"))} | ${escapeMarkdown(String(item.message || ""))} |`).join("\n") || "| - | - | none |";
  const coverageRows = (coverage || []).map((item) => `| ${escapeMarkdown(item.requirement_id)} | ${escapeMarkdown(item.priority || "-")} | ${escapeMarkdown(item.intent || "-")} | ${escapeMarkdown(item.plan_status || "-")} | ${escapeMarkdown(item.execution_status || "-")} | ${escapeMarkdown(item.evidence || "-")} | ${escapeMarkdown(item.reason || "")} |`).join("\n") || "| - | - | - | - | - | - | none |";
  const caseRows = (cases || []).map((item) => `| ${escapeMarkdown(item.case_id)} | ${escapeMarkdown(item.title || "-")} | ${escapeMarkdown(item.origin?.type || planSource || "-")} | ${escapeMarkdown(item.risk || "-")} | ${item.steps?.length || 0} |`).join("\n") || "| - | - | - | - | 0 |";
  const metricRows = Object.entries(coverageMetrics || {}).map(([name, value]) => `| ${escapeMarkdown(name)} | ${value}% |`).join("\n") || "| - | - |";
  const warning = gate === "incomplete" || auditStatus === "INCOMPLETE" ? "\n> Overall audit is incomplete. Passing executed cases must not be interpreted as project approval.\n" : "";
  const markdown = `# AutoPW Audit Report\n\n- Run: ${escapeMarkdown(runId)}\n- Gate: **${escapeMarkdown(gate)}**\n- Audit: **${escapeMarkdown(auditStatus)}**\n- Target: ${escapeMarkdown(target || "managed")}\n- Plan source: **${escapeMarkdown(planSource || "generated")}**\n- Results: ${escapeMarkdown(resultsRef.handle)}\n${warning}\n## Summary\n\n\`${escapeMarkdown(JSON.stringify(safeSummary))}\`\n\n## Coverage Metrics\n\n| Metric | Value |\n|---|---:|\n${metricRows}\n\n## Requirement Coverage\n\n| Requirement | Priority | Intent | Plan | Execution | Evidence | Reason |\n|---|---|---|---|---|---|---|\n${coverageRows}\n\n## Case Paths\n\n| Case | Title | Plan source | Risk | Test steps |\n|---|---|---|---|---:|\n${caseRows}\n\n## Issues\n\n| Execution | Classification | Message |\n|---|---|---|\n${issueRows}\n`;
  const reportRef = storage.writeArtifact(runId, "report.md", "report.md", markdown);
  const html = `<!doctype html><meta charset="utf-8"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; img-src 'self' data:; style-src 'unsafe-inline'; base-uri 'none'; form-action 'none'"><title>AutoPW Report</title><h1>AutoPW Audit Report</h1><p>Gate: <strong>${escapeHtml(gate)}</strong></p><p>Audit: <strong>${escapeHtml(auditStatus)}</strong></p><p>Plan source: <strong>${escapeHtml(planSource || "generated")}</strong></p><h2>Coverage Metrics</h2><pre>${escapeHtml(JSON.stringify(redactSecrets(coverageMetrics || {}), null, 2))}</pre><h2>Requirement Coverage</h2><pre>${escapeHtml(JSON.stringify(redactSecrets(coverage || []), null, 2))}</pre><h2>Case Paths</h2><pre>${escapeHtml(JSON.stringify(redactSecrets(cases || []), null, 2))}</pre><pre>${escapeHtml(JSON.stringify(redactSecrets({ summary, issues }), null, 2))}</pre>`;
  const htmlRef = storage.writeArtifact(runId, "report.html", "report.html", html);
  return { reportRef, htmlRef };
}

function escapeHtml(value: string): string { return value.replace(/[&<>"']/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "\"": "&quot;", "'": "&#39;" }[char] || char)); }
function escapeMarkdown(value: string): string { return value.replace(/[&<>|`\\]/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "|": "\\|", "`": "\\`", "\\": "\\\\" }[char] || char)).replace(/[\r\n]+/g, " "); }
