// GENERATED by tools/gen-types.mjs from packages/schemas/src/enums.mjs.
// Do not edit by hand; verify:m0 diffs these literals against the enums module.

export const runPhase =   ["CREATED", "TARGET_READY", "SEED_RESOLVED", "DISCOVERED", "COVERAGE_DERIVED", "PLAN_FILLED", "PLAN_FROZEN", "SUITE_GENERATED", "SUITE_FROZEN", "RUNNING", "EXECUTION_FINISHED", "RUNTIME_FINALIZED", "TERMINALIZING", "AUDITED", "REPORTED", "GATED"] as const;
export type RunPhase = typeof runPhase[number];

export const runPhaseNormal =   ["CREATED", "TARGET_READY", "SEED_RESOLVED", "DISCOVERED", "COVERAGE_DERIVED", "PLAN_FILLED", "PLAN_FROZEN", "SUITE_GENERATED", "SUITE_FROZEN", "RUNNING", "EXECUTION_FINISHED", "RUNTIME_FINALIZED", "AUDITED", "REPORTED", "GATED"] as const;
export type RunPhaseNormal = typeof runPhaseNormal[number];

export const runStatus =   ["ACTIVE", "INTERRUPTED", "FAILED", "COMPLETED"] as const;
export type RunStatus = typeof runStatus[number];

export const auditStatus =   ["COMPLETE", "INCOMPLETE"] as const;
export type AuditStatus = typeof auditStatus[number];

export const operationStatus =   ["ACCEPTED", "RUNNING", "COMPLETED", "FAILED", "CANCELLED"] as const;
export type OperationStatus = typeof operationStatus[number];

export const gate =   ["incomplete", "infra", "fail", "unstable", "pass"] as const;
export type Gate = typeof gate[number];

export const gatePriority =   ["incomplete", "infra", "fail", "unstable", "pass"] as const;
export type GatePriority = typeof gatePriority[number];

export const baseTier =   ["smoke", "fast", "full"] as const;
export type BaseTier = typeof baseTier[number];

export const scenario =   ["normal", "required_field", "invalid_input", "boundary", "empty_state", "service_error", "network_failure"] as const;
export type Scenario = typeof scenario[number];

export const executionStatus =   ["NOT_RUN", "RUNNING", "PASSED", "FAILED", "FLAKY", "INTERRUPTED", "BLOCKED_RESUME", "INFRA_BLOCKED"] as const;
export type ExecutionStatus = typeof executionStatus[number];

export const executionTerminal =   ["PASSED", "FAILED", "FLAKY"] as const;
export type ExecutionTerminal = typeof executionTerminal[number];

export const priority =   ["P0", "P1", "P2"] as const;
export type Priority = typeof priority[number];

export const issueClassification =   ["PRODUCT_DEFECT", "TEST_DEFECT", "PLAN_DEFECT", "INFRA_DEFECT", "FLAKY"] as const;
export type IssueClassification = typeof issueClassification[number];

export const classificationConfidence =   ["HIGH", "MEDIUM", "LOW"] as const;
export type ClassificationConfidence = typeof classificationConfidence[number];

export const trustMode =   ["trusted", "untrusted_pr"] as const;
export type TrustMode = typeof trustMode[number];

export const lifecycleMode =   ["connect", "manage"] as const;
export type LifecycleMode = typeof lifecycleMode[number];

export const gateStrategy =   ["product", "strict"] as const;
export type GateStrategy = typeof gateStrategy[number];

export const terminalizationReason =   ["PLAN_DEFECT", "SEED_EXHAUSTED", "TEST_DEFECT_UNSAFE", "INFRA_BLOCKED_GLOBAL", "BUDGET_EXCEEDED", "CANCEL_REQUESTED"] as const;
export type TerminalizationReason = typeof terminalizationReason[number];

export const fatalFailureClass =   ["STORAGE_INTEGRITY", "SCHEMA_BUNDLE_INVALID", "TRUST_BOUNDARY_BROKEN", "DIRECTORY_ANCHOR_LOST", "STATE_CORRUPTED"] as const;
export type FatalFailureClass = typeof fatalFailureClass[number];

export const toolResultKind =   ["ok", "error"] as const;
export type ToolResultKind = typeof toolResultKind[number];

export const LIMITS = {
  "workspaceId": {
    "max": 128,
    "pattern": "^[A-Za-z0-9_.:-]+$"
  },
  "projectSubpath": {
    "max": 320,
    "pattern": "^[A-Za-z0-9_./@\\-]+$"
  },
  "clientRequestId": {
    "max": 160,
    "pattern": "^[A-Za-z0-9_.:-]+$"
  },
  "operationId": {
    "max": 64,
    "pattern": "^op_[A-Za-z0-9]{20}$"
  },
  "runId": {
    "max": 64,
    "pattern": "^run_[A-Za-z0-9]{20}$"
  },
  "handleToken": {
    "max": 96,
    "pattern": "^[A-Za-z0-9_-]{32,}$"
  },
  "caseId": {
    "max": 96,
    "pattern": "^[A-Za-z0-9_.:-]+$"
  },
  "executionId": {
    "max": 96,
    "pattern": "^EXE-[A-Za-z0-9]{16}$"
  },
  "batchId": {
    "max": 96,
    "pattern": "^BAT-[A-Za-z0-9]{16}$"
  },
  "featureId": {
    "max": 96,
    "pattern": "^[A-Za-z0-9_.:-]+$"
  },
  "schemaVersionPattern": "^2\\.(1)(\\.[0-9]+)?(-rc[0-9]+)?(-mcp-first)?$",
  "untrustedText": {
    "max": 5000
  },
  "descriptionText": {
    "max": 1000
  },
  "payloadBytesSoft": {
    "max": 524288
  },
  "payloadBytesHard": {
    "max": 16777216
  },
  "pollAfterMsMin": {
    "min": 0
  },
  "pollAfterMsMax": {
    "min": 600000
  },
  "leaseTtlMs": {
    "min": 30000
  },
  "heartbeatMs": {
    "max": 10000
  },
  "clockSkewMs": {
    "max": 5000
  },
  "takeoverConfirmMs": {
    "min": 30000
  },
  "maxExecutionInstancesPerRun": {
    "min": 1
  },
  "matrixBudgetMaxExecutionInstances": {
    "min": 1
  },
  "retentionTtlMsMin": {
    "min": 1000
  }
} as const;
export type Limits = typeof LIMITS;

