import crypto from "node:crypto";
import type { FixturePlan } from "@autopw/execution-fixture";
import { assertValidPlan, TEST_PLAN_SCHEMA_V1_0, TEST_PLAN_SCHEMA_V1_1, type TestPlan, type TestStep } from "@autopw/test-plan";
import type { CandidateCatalog, PlannerOutput } from "@autopw/planner";

export interface RequirementLike { requirement_id: string; feature_id: string; intent: string; scenario: string; priority: "P0" | "P1" | "P2"; risk: "read_only" | "mutating" | "destructive"; confidence: number; status: string; oracle: { kind: string; assertion: string; details?: Record<string, unknown> } | null; payload_strategy?: { valid_payload?: Record<string, unknown>; invalid_payload?: Record<string, unknown>; boundary_payloads?: Record<string, unknown>[] }; fixture_strategy?: { kind: string; proven: boolean; payload?: Record<string, unknown>; create?: { operation_id: string; method: string; path: string }; read?: { operation_id: string; method: string; path: string }; update?: { operation_id: string; method: string; path: string }; cleanup?: { operation_id: string; method: string; path: string }; identity?: { kind: "response_body" | "location_header" | "explicit" | "none"; path?: string; header?: string; proven: boolean } }; oracle_specification?: { kind: string; assertion: string; proven: boolean }; }
export interface DeclarativeMappingAudit { required_requirement_ids: string[]; planned_requirement_ids: string[]; generated_case_ids: string[]; requirement_case_map: Record<string, string[]>; requirement_oracle_map: Record<string, string[]>; case_step_map: Record<string, string[]>; unmapped_requirements: { requirement_id: string; reason: string }[]; match: "COMPLETE" | "PARTIAL" | "MISMATCH"; }
export interface CompiledSuite { plan: FixturePlan | TestPlan; source: string; mappingAudit: { planned_case_ids?: string[]; generated_case_ids: string[]; match: "COMPLETE" | "PARTIAL" | "MISMATCH"; required_requirement_ids?: string[]; planned_requirement_ids?: string[]; requirement_case_map?: Record<string, string[]>; requirement_oracle_map?: Record<string, string[]>; case_step_map?: Record<string, string[]>; unmapped_requirements?: { requirement_id: string; reason: string }[] }; digest?: string; }

export function compileFixturePlan(plan: FixturePlan): CompiledSuite {
  const source = ["// generated by AutoPW deterministic M2 compiler", "// execution is delegated to the trusted execution-fixture adapter", ...plan.cases.map((item) => `export const ${item.case_id.replace(/[^A-Za-z0-9_]/g, "_")} = ${JSON.stringify(item.steps)};`)].join("\n") + "\n";
  assertSafeGeneratedSource(source);
  const ids = plan.cases.map((item) => item.case_id);
  return { plan, source, mappingAudit: { planned_case_ids: ids, generated_case_ids: [...ids], match: "COMPLETE" }, digest: suiteDigest(source) };
}

export function compileTestPlan({ requirements, candidateCatalog, plannerOutput, manualOverlay = {} }: { requirements: RequirementLike[]; candidateCatalog: CandidateCatalog; plannerOutput: PlannerOutput; manualOverlay?: Record<string, unknown> }): { plan: TestPlan; source: string; mappingAudit: DeclarativeMappingAudit; digest: string } {
  const requirementByCase = new Map(requirements.map((item) => [requirementCaseId(item.requirement_id), item]));
  const selections = [...plannerOutput.caseSelections].sort((a, b) => a.caseId.localeCompare(b.caseId));
  const cases: TestPlan["cases"] = [];
  const requirementCaseMap: Record<string, string[]> = {};
  const requirementOracleMap: Record<string, string[]> = {};
  const caseStepMap: Record<string, string[]> = {};
  const unmapped: { requirement_id: string; reason: string }[] = [];
  for (const selection of selections) {
    const requirement = requirementByCase.get(selection.caseId);
    if (!requirement) continue;
    const selectedActions = [...selection.actionSelections].sort((a, b) => a.actionTemplateId.localeCompare(b.actionTemplateId));
    const selectedExpectations = [...selection.expectationIds].sort();
    const generated = buildRequirementExecution(requirement, selection.caseId, selectedActions, selectedExpectations, candidateCatalog);
    const steps = generated.steps;
    if (steps.length === 0) { unmapped.push({ requirement_id: requirement.requirement_id, reason: "NO_SELECTED_STEPS" }); continue; }
    const kind = steps.some((step) => step.action === "api_request") && steps.some((step) => step.action !== "api_request" && step.action !== "expect_status") ? "hybrid" : steps.some((step) => step.action === "api_request") ? "api" : "ui";
    const effectiveTier = tierForRequirement(requirement);
    cases.push({ case_id: selection.caseId, origin: { type: "generated", source_ref: "m9.7:planner" }, title: `${requirement.intent} for ${requirement.feature_id}`, feature_id: requirement.feature_id, requirement_refs: [requirement.requirement_id], ...(generated.oracleBindings.length ? { oracle_bindings: [{ requirement_id: requirement.requirement_id, step_refs: generated.oracleBindings.map((value) => value.slice(value.lastIndexOf(":") + 1)) }] } : {}), scenario: validScenario(requirement.scenario), priority: requirement.priority, effective_tier: effectiveTier, kind, risk: requirement.risk, confidence: requirement.confidence, execution_policy: { production_allowed: requirement.risk === "read_only", isolated_fixture_required: requirement.risk !== "read_only" }, ...(generated.setup.length ? { setup: generated.setup } : {}), steps, ...(generated.cleanup.length ? { cleanup: generated.cleanup } : {}) });
    requirementCaseMap[requirement.requirement_id] = [selection.caseId];
    if (generated.oracleBindings.length > 0) requirementOracleMap[requirement.requirement_id] = generated.oracleBindings;
    else unmapped.push({ requirement_id: requirement.requirement_id, reason: "MISSING_ORACLE_BINDING" });
    caseStepMap[selection.caseId] = [...generated.setup, ...steps, ...generated.cleanup].map((_step, index) => `${selection.caseId}:step_${index}`);
  }
  for (const requirement of requirements) if (requirement.status !== "TIER_SKIPPED" && requirement.status !== "NOT_APPLICABLE" && !requirementCaseMap[requirement.requirement_id]) unmapped.push({ requirement_id: requirement.requirement_id, reason: requirement.status === "BLOCKED" ? requirement.oracle === null ? "MISSING_ORACLE" : "BLOCKED" : "NOT_PLANNED" });
  const requiredIds = requirements.filter((item) => item.status !== "TIER_SKIPPED" && item.status !== "NOT_APPLICABLE").map((item) => item.requirement_id).sort();
  const plannedIds = cases.flatMap((item) => item.requirement_refs).sort();
  const mappingAudit: DeclarativeMappingAudit = { required_requirement_ids: requiredIds, planned_requirement_ids: plannedIds, generated_case_ids: cases.map((item) => item.case_id).sort(), requirement_case_map: sortRecord(requirementCaseMap), requirement_oracle_map: sortRecord(requirementOracleMap), case_step_map: sortRecord(caseStepMap), unmapped_requirements: dedupeUnmapped(unmapped), match: unmapped.length === 0 && requiredIds.every((id) => plannedIds.includes(id)) ? "COMPLETE" : cases.length > 0 ? "PARTIAL" : "MISMATCH" };
  const usesSemanticSteps = cases.some((item) => [...(item.setup || []), ...item.steps, ...(item.cleanup || [])].some((step) => step.action === "expect_relation" || step.action === "expect_collection"));
  const plan: TestPlan = { plan_schema: usesSemanticSteps ? TEST_PLAN_SCHEMA_V1_1 : TEST_PLAN_SCHEMA_V1_0, plan_id: "generated-" + shortDigest(requirements.map((item) => item.requirement_id).sort().join("|")), generated_at: "2026-08-07T00:00:00.000Z", origin: { type: "generated", source_ref: "m9.7:planner", generator_version: "2.1.0-m11.5" }, coverage_eligible: mappingAudit.match === "COMPLETE", cases };
  assertValidPlan(plan, { authority: "generated" });
  const source = ["// generated by AutoPW declarative M9.7 compiler", "// manual overlay keys: " + Object.keys(manualOverlay).sort().join(","), ...cases.map((item) => `export const ${item.case_id.replace(/[^A-Za-z0-9_]/g, "_")} = ${JSON.stringify(item.steps)};`)].join("\n") + "\n";
  assertSafeGeneratedSource(source);
  const digest = suiteDigest(stableJson({ plan, mappingAudit }));
  return { plan, source, mappingAudit, digest };
}

function buildRequirementExecution(requirement: RequirementLike, caseId: string, selectedActions: Array<{ actionTemplateId: string; locatorId?: string }>, selectedExpectations: string[], catalog: CandidateCatalog): { setup: TestStep[]; steps: TestStep[]; cleanup: TestStep[]; oracleBindings: string[] } {
  const actionCandidate = selectedActions.map((item) => catalog.actions[item.actionTemplateId]).find(Boolean);
  if (!actionCandidate?.step) return { setup: [], steps: [], cleanup: [], oracleBindings: [] };
  const primary = JSON.parse(JSON.stringify(actionCandidate.step)) as TestStep;
  const safeRequirement = requirement.requirement_id.replace(/[^A-Za-z0-9_.:-]+/g, "_");
  const responseName = "response_" + safeRequirement;
  if (primary.action === "api_request") primary.save_as = responseName;
  const setup: TestStep[] = [];
  const cleanup: TestStep[] = [];
  const steps: TestStep[] = [];
  const primaryApi = primary.action === "api_request" ? primary : undefined;
  const fixturePriority = priorityForFeature(catalog, requirement.feature_id);
  const collectionPath = primaryApi ? collectionPathFor(requirement, primaryApi) : "/";
  const setupResponse = "setup_" + safeRequirement;
  const setupSecondaryResponse = "setup_secondary_" + safeRequirement;
  const idPath = fixturePath(requirement, setupResponse, "read", primaryApi?.path || collectionPath);
  const needsItem = ["route_detail", "completed_state", "update_persists", "delete_removes_entity"].includes(requirement.intent);
  if (needsItem) {
    setup.push({ action: "api_request", method: "POST", path: collectionPath, body: fixtureBody(requirement, "AutoPW fixture", fixturePriority), save_as: setupResponse, acceptable_statuses: [201] });
    if (primaryApi) primaryApi.path = idPath;
    if (requirement.intent === "delete_removes_entity") cleanup.push({ action: "api_request", method: "GET", path: idPath, acceptable_statuses: [404] });
    else cleanup.push({ action: "api_request", method: "DELETE", path: fixturePath(requirement, setupResponse, "cleanup", idPath), acceptable_statuses: [204] });
  }
  if (requirement.intent === "create_succeeds") cleanup.push({ action: "api_request", method: "DELETE", path: fixturePath(requirement, responseName, "cleanup", `${collectionPath}/\${responses.${responseName}.body.id}`), acceptable_statuses: [204] });
  if (requirement.intent === "search_filters_results") {
    setup.push({ action: "api_request", method: "POST", path: collectionPath, body: fixtureBody(requirement, "AutoPW", fixturePriority), save_as: setupResponse, acceptable_statuses: [201] });
    setup.push({ action: "api_request", method: "POST", path: collectionPath, body: fixtureBody(requirement, "OtherPW", fixturePriority), save_as: setupSecondaryResponse, acceptable_statuses: [201] });
    cleanup.push({ action: "api_request", method: "DELETE", path: fixturePath(requirement, setupResponse, "cleanup", collectionPath), acceptable_statuses: [204] });
    cleanup.push({ action: "api_request", method: "DELETE", path: fixturePath(requirement, setupSecondaryResponse, "cleanup", collectionPath), acceptable_statuses: [204] });
  }
  const oracleBindings: string[] = [];
  const appendAssertion = (step: TestStep, bind = true): void => {
    if (bind) oracleBindings.push(`${caseId}:step_${setup.length + steps.length}`);
    steps.push(step);
  };
  steps.push(primary);
  if (requirement.intent === "create_succeeds") {
    const refreshName = "refresh_" + safeRequirement;
    steps.push({ action: "api_request", method: "GET", path: fixturePath(requirement, responseName, "read", collectionPath), save_as: refreshName });
  }
  if (requirement.intent === "count_consistent") steps.push({ action: "api_request", method: "GET", path: typeof requirement.oracle?.details?.collection_path === "string" ? requirement.oracle.details.collection_path : collectionPath, save_as: "list_" + safeRequirement });
  if (["completed_state", "update_persists"].includes(requirement.intent)) {
    const rereadName = "reread_" + safeRequirement;
    steps.push({ action: "api_request", method: "GET", path: idPath, save_as: rereadName });
  }
  const hasCandidateOracle = selectedExpectations.some((id) => Boolean(catalog.expectations[id]));
  const semanticRequired = ["create_succeeds", "update_persists", "summary_is_consistent", "count_consistent", "search_filters_results"].includes(requirement.intent);
  let semanticComplete = !semanticRequired;
  const expectedStatus = typeof requirement.oracle?.details?.status === "number" ? Number(requirement.oracle.details.status) : ["required_field_rejected", "enum_validation"].includes(requirement.intent) ? 400 : 200;
  appendAssertion({ action: "expect_status", source: `responses.${responseName}`, equals: expectedStatus }, !semanticRequired);
  if (requirement.intent === "create_succeeds" && !semanticRequired) appendAssertion({ action: "expect_json", source: `responses.${responseName}`, path: "id", exists: true });
  if (requirement.intent === "route_detail") appendAssertion({ action: "expect_json", source: `responses.${responseName}`, path: "id", exists: true });
  if (requirement.intent === "completed_state") appendAssertion({ action: "expect_json", source: `responses.reread_${safeRequirement}`, path: "completed", equals: true });
  if (requirement.intent === "delete_removes_entity") {
    const deleteReadback = "delete_readback_" + safeRequirement;
    steps.push({ action: "api_request", method: "GET", path: idPath, save_as: deleteReadback });
    appendAssertion({ action: "expect_status", source: `responses.${deleteReadback}`, equals: 404 });
  }
  if (requirement.oracle_specification?.proven !== false && requirement.intent === "create_succeeds") {
    const identity = requirement.fixture_strategy?.identity;
    const identityPath = identity?.path?.replace(/^body\./, "") || "id";
    if (identity?.kind === "location_header") appendAssertion({ action: "expect_relation", left: { source: `responses.refresh_${safeRequirement}`, path: "$response.status" }, operator: "equals", right: { literal: 200 } });
    else appendAssertion({ action: "expect_relation", left: { source: `responses.refresh_${safeRequirement}`, path: identityPath }, operator: "equals", right: { source: `responses.${responseName}`, path: identityPath } });
    semanticComplete = true;
  }
  if (requirement.oracle_specification?.proven !== false && requirement.intent === "update_persists") {
    const field = Object.keys(requirement.payload_strategy?.valid_payload || {})[0];
    if (field) { appendAssertion({ action: "expect_relation", left: { source: `responses.reread_${safeRequirement}`, path: field }, operator: "equals", right: { source: `responses.${responseName}`, path: field } }); semanticComplete = true; }
  }
  if (requirement.oracle_specification?.proven !== false && requirement.intent === "summary_is_consistent") {
    appendAssertion({ action: "expect_relation", left: { source: `responses.${responseName}`, path: "total" }, operator: "greater_or_equal", right: { source: `responses.${responseName}`, path: "completed" } });
    semanticComplete = true;
  }
  if (requirement.oracle_specification?.proven !== false && requirement.intent === "count_consistent") {
    appendAssertion({ action: "expect_relation", left: { source: `responses.${responseName}`, path: "count" }, operator: "equals", right: { source: `responses.list_${safeRequirement}`, aggregate: "length" } });
    semanticComplete = true;
  }
  if (requirement.oracle_specification?.proven !== false && requirement.intent === "search_filters_results") {
    const field = Object.keys(requirement.fixture_strategy?.payload || {}).find((key) => typeof requirement.fixture_strategy?.payload?.[key] === "string") || "title";
    appendAssertion({ action: "expect_collection", source: `responses.${responseName}`, quantifier: "every", predicate: { path: field, operator: "contains", value: "AutoPW" } });
    semanticComplete = true;
  }
  if (requirement.intent === "cors_allows_operation") appendAssertion({ action: "expect_header", source: `responses.${responseName}`, name: "access-control-allow-methods", contains: "PATCH" });
  return { setup, steps, cleanup, oracleBindings: hasCandidateOracle && semanticComplete ? oracleBindings : [] };
}

function collectionPathFor(requirement: RequirementLike, primary: Extract<TestStep, { action: "api_request" }>): string {
  const fixtureCreate = requirement.fixture_strategy?.create?.path;
  if (fixtureCreate) return String(fixtureCreate).split("?")[0] || "/";
  const primaryPath = String(primary.path).split("?")[0];
  if (primary.method === "POST" && !primaryPath.includes(":id") && !primaryPath.includes("${")) return primaryPath || "/";
  return primaryPath || "/";
}
function fixturePath(requirement: RequirementLike, responseName: string, role: "read" | "update" | "cleanup", fallback: string): string {
  const fixture = requirement.fixture_strategy;
  const target = fixture?.[role]?.path || fallback;
  const identity = fixture?.identity;
  if (identity?.kind === "location_header") return `\${responses.${responseName}.headers.${identity.header || "location"}}`;
  if (identity?.kind === "explicit" && identity.path) return replacePathIdentity(target, identity.path);
  if (identity?.kind === "response_body" && identity.path) return replacePathIdentity(target, `\${responses.${responseName}.body.${identity.path.replace(/^body\./, "")}}`);
  return target;
}
function replacePathIdentity(path: string, identity: string): string { return path.replace(/:[A-Za-z0-9_]+/, identity); }
function fixtureBody(requirement: RequirementLike, marker: string, fallbackPriority: string): Record<string, unknown> { const base = { ...(requirement.fixture_strategy?.payload || {}) }; const stringField = Object.keys(base).find((key) => typeof base[key] === "string"); if (stringField) base[stringField] = marker; return Object.keys(base).length ? base : { title: marker, priority: fallbackPriority }; }
function tierForRequirement(requirement: RequirementLike): "smoke" | "fast" | "full" {
  if (requirement.priority === "P2") return "full";
  if (requirement.priority === "P1") return "fast";
  return ["invalid_input", "empty_state", "boundary"].includes(requirement.scenario) ? "fast" : "smoke";
}
function priorityForFeature(catalog: CandidateCatalog, featureId: string): string {
  for (const action of Object.values(catalog.actions)) {
    if (action.feature_id !== featureId || !action.step || typeof action.step.body !== "object" || action.step.body === null) continue;
    const priority = (action.step.body as Record<string, unknown>).priority;
    if (typeof priority === "string" && priority !== "unsupported") return priority;
  }
  return "normal";
}

export function assertSafeGeneratedSource(source: string): void {
  if (/(?:node:|child_process|\brequire\s*\(|import\s+.*from\s+['"]playwright)/i.test(source)) throw new Error("GENERATED_SUITE_FORBIDDEN_IMPORT");
}

export function suiteDigest(source: string): string { return crypto.createHash("sha256").update(source).digest("hex"); }
function requirementCaseId(requirementId: string): string { return "case_" + requirementId.replace(/[^A-Za-z0-9_.:-]+/g, "_"); }
function validScenario(value: string): TestPlan["cases"][number]["scenario"] { return (["normal", "required_field", "invalid_input", "empty_state", "boundary", "service_error", "network_failure", "not_found", "persistence", "cors"] as string[]).includes(value) ? value as TestPlan["cases"][number]["scenario"] : "normal"; }
function shortDigest(value: string): string { return crypto.createHash("sha256").update(value).digest("hex").slice(0, 16); }
function stableJson(value: unknown): string { if (Array.isArray(value)) return "[" + value.map(stableJson).join(",") + "]"; if (value && typeof value === "object") return "{" + Object.entries(value as Record<string, unknown>).sort(([a], [b]) => a.localeCompare(b)).map(([key, item]) => JSON.stringify(key) + ":" + stableJson(item)).join(",") + "}"; return JSON.stringify(value); }
function sortRecord(value: Record<string, string[]>): Record<string, string[]> { return Object.fromEntries(Object.entries(value).sort(([a], [b]) => a.localeCompare(b)).map(([key, items]) => [key, [...items].sort()])); }
function dedupeUnmapped(items: { requirement_id: string; reason: string }[]): { requirement_id: string; reason: string }[] { return [...new Map(items.map((item) => [item.requirement_id, item])).values()].sort((a, b) => a.requirement_id.localeCompare(b.requirement_id)); }
