import crypto from "node:crypto";
import type { FixturePlan } from "@autopw/execution-fixture";
import { assertValidPlan, TEST_PLAN_SCHEMA_V1_0, TEST_PLAN_SCHEMA_V1_1, type TestPlan, type TestStep } from "@autopw/test-plan";
import type { CandidateCatalog, PlannerOutput } from "@autopw/planner";

export interface RequirementLike { requirement_id: string; feature_id: string; intent: string; scenario: string; priority: "P0" | "P1" | "P2"; risk: "read_only" | "mutating" | "destructive"; confidence: number; status: string; oracle: { kind: string; assertion: string; details?: Record<string, unknown> } | null; payload_strategy?: { valid_payload?: Record<string, unknown>; invalid_payload?: Record<string, unknown>; boundary_payloads?: Record<string, unknown>[] }; fixture_strategy?: { kind: string; proven: boolean; payload?: Record<string, unknown>; create?: { operation_id: string; method: string; path: string }; read?: { operation_id: string; method: string; path: string }; update?: { operation_id: string; method: string; path: string }; cleanup?: { operation_id: string; method: string; path: string }; identity?: { kind: "response_body" | "location_header" | "explicit" | "none"; path?: string; header?: string; proven: boolean } }; oracle_specification?: { kind: string; assertion: string; proven: boolean }; }
export interface DeclarativeMappingAudit { required_requirement_ids: string[]; planned_requirement_ids: string[]; generated_case_ids: string[]; requirement_case_map: Record<string, string[]>; requirement_oracle_map: Record<string, string[]>; case_step_map: Record<string, string[]>; unmapped_requirements: { requirement_id: string; reason: string }[]; match: "COMPLETE" | "PARTIAL" | "MISMATCH"; }
export interface CompiledSuite { plan: FixturePlan | TestPlan; source: string; mappingAudit: { planned_case_ids?: string[]; generated_case_ids: string[]; match: "COMPLETE" | "PARTIAL" | "MISMATCH"; required_requirement_ids?: string[]; planned_requirement_ids?: string[]; requirement_case_map?: Record<string, string[]>; requirement_oracle_map?: Record<string, string[]>; case_step_map?: Record<string, string[]>; unmapped_requirements?: { requirement_id: string; reason: string }[] }; digest?: string; }

export function compileFixturePlan(plan: FixturePlan): CompiledSuite {
  const source = ["// generated by AutoPW deterministic M2 compiler", "// execution is delegated to the trusted execution-fixture adapter", ...plan.cases.map((item) => `export const ${item.case_id.replace(/[^A-Za-z0-9_]/g, "_")} = ${JSON.stringify(item.steps)};`)].join("\n") + "\n";
  assertSafeGeneratedSource(source);
  const ids = plan.cases.map((item) => item.case_id);
  return { plan, source, mappingAudit: { planned_case_ids: ids, generated_case_ids: [...ids], match: "COMPLETE" }, digest: suiteDigest(source) };
}

export function compileTestPlan({ requirements, candidateCatalog, plannerOutput, manualOverlay = {} }: { requirements: RequirementLike[]; candidateCatalog: CandidateCatalog; plannerOutput: PlannerOutput; manualOverlay?: Record<string, unknown> }): { plan: TestPlan; source: string; mappingAudit: DeclarativeMappingAudit; digest: string } {
  const requirementByCase = new Map(requirements.map((item) => [requirementCaseId(item.requirement_id), item]));
  const selections = [...plannerOutput.caseSelections].sort((a, b) => a.caseId.localeCompare(b.caseId));
  const cases: TestPlan["cases"] = [];
  const requirementCaseMap: Record<string, string[]> = {};
  const requirementOracleMap: Record<string, string[]> = {};
  const caseStepMap: Record<string, string[]> = {};
  const unmapped: { requirement_id: string; reason: string }[] = [];
  for (const selection of selections) {
    const requirement = requirementByCase.get(selection.caseId);
    if (!requirement) continue;
    const selectedActions = [...selection.actionSelections].sort((a, b) => a.actionTemplateId.localeCompare(b.actionTemplateId));
    const selectedExpectations = [...selection.expectationIds].sort();
    const generated = buildRequirementExecution(requirement, selection.caseId, selectedActions, selectedExpectations, candidateCatalog);
    const steps = generated.steps;
    if (steps.length === 0) { unmapped.push({ requirement_id: requirement.requirement_id, reason: "NO_SELECTED_STEPS" }); continue; }
    const allSteps = [...generated.setup, ...steps, ...generated.cleanup];
    const hasApi = allSteps.some((step) => step.action === "api_request");
    const hasUi = allSteps.some((step) => UI_ACTIONS.has(step.action));
    const kind = hasApi && hasUi ? "hybrid" : hasUi ? "ui" : "api";
    const effectiveTier = tierForRequirement(requirement);
    cases.push({ case_id: selection.caseId, origin: { type: "generated", source_ref: "m9.7:planner" }, title: `${requirement.intent} for ${requirement.feature_id}`, feature_id: requirement.feature_id, requirement_refs: [requirement.requirement_id], ...(generated.oracleBindings.length ? { oracle_bindings: [{ requirement_id: requirement.requirement_id, step_refs: generated.oracleBindings.map((value) => value.slice(value.lastIndexOf(":") + 1)) }] } : {}), scenario: validScenario(requirement.scenario), priority: requirement.priority, effective_tier: effectiveTier, kind, risk: requirement.risk, confidence: requirement.confidence, execution_policy: { production_allowed: requirement.risk === "read_only", isolated_fixture_required: requirement.risk !== "read_only" }, ...(generated.setup.length ? { setup: generated.setup } : {}), steps, ...(generated.cleanup.length ? { cleanup: generated.cleanup } : {}) });
    requirementCaseMap[requirement.requirement_id] = [selection.caseId];
    if (generated.oracleBindings.length > 0) requirementOracleMap[requirement.requirement_id] = generated.oracleBindings;
    else unmapped.push({ requirement_id: requirement.requirement_id, reason: "MISSING_ORACLE_BINDING" });
    caseStepMap[selection.caseId] = [...generated.setup, ...steps, ...generated.cleanup].map((_step, index) => `${selection.caseId}:step_${index}`);
  }
  for (const requirement of requirements) if (requirement.status !== "TIER_SKIPPED" && requirement.status !== "NOT_APPLICABLE" && !requirementCaseMap[requirement.requirement_id]) unmapped.push({ requirement_id: requirement.requirement_id, reason: requirement.status === "BLOCKED" ? requirement.oracle === null ? "MISSING_ORACLE" : "BLOCKED" : "NOT_PLANNED" });
  const requiredIds = requirements.filter((item) => item.status !== "TIER_SKIPPED" && item.status !== "NOT_APPLICABLE").map((item) => item.requirement_id).sort();
  const plannedIds = cases.flatMap((item) => item.requirement_refs).sort();
  const mappingAudit: DeclarativeMappingAudit = { required_requirement_ids: requiredIds, planned_requirement_ids: plannedIds, generated_case_ids: cases.map((item) => item.case_id).sort(), requirement_case_map: sortRecord(requirementCaseMap), requirement_oracle_map: sortRecord(requirementOracleMap), case_step_map: sortRecord(caseStepMap), unmapped_requirements: dedupeUnmapped(unmapped), match: unmapped.length === 0 && requiredIds.every((id) => plannedIds.includes(id)) ? "COMPLETE" : cases.length > 0 ? "PARTIAL" : "MISMATCH" };
  const usesSemanticSteps = cases.some((item) => [...(item.setup || []), ...item.steps, ...(item.cleanup || [])].some((step) => step.action === "expect_relation" || step.action === "expect_collection"));
  const plan: TestPlan = { plan_schema: usesSemanticSteps ? TEST_PLAN_SCHEMA_V1_1 : TEST_PLAN_SCHEMA_V1_0, plan_id: "generated-" + shortDigest(requirements.map((item) => item.requirement_id).sort().join("|")), generated_at: "2026-08-07T00:00:00.000Z", origin: { type: "generated", source_ref: "m9.7:planner", generator_version: "2.1.0-m11.5" }, coverage_eligible: mappingAudit.match === "COMPLETE", cases };
  assertValidPlan(plan, { authority: "generated" });
  const source = ["// generated by AutoPW declarative M9.7 compiler", "// manual overlay keys: " + Object.keys(manualOverlay).sort().join(","), ...cases.map((item) => `export const ${item.case_id.replace(/[^A-Za-z0-9_]/g, "_")} = ${JSON.stringify(item.steps)};`)].join("\n") + "\n";
  assertSafeGeneratedSource(source);
  const digest = suiteDigest(stableJson({ plan, mappingAudit }));
  return { plan, source, mappingAudit, digest };
}

function buildRequirementExecution(requirement: RequirementLike, caseId: string, selectedActions: Array<{ actionTemplateId: string; locatorId?: string }>, selectedExpectations: string[], catalog: CandidateCatalog): { setup: TestStep[]; steps: TestStep[]; cleanup: TestStep[]; oracleBindings: string[] } {
  const uiBehavior = buildUiBehaviorExecution(requirement, caseId);
  if (uiBehavior) return uiBehavior;
  if (requirement.intent === "route_detail") return buildDetailConsistencyExecution(requirement, caseId);
  const runtimeCrud = buildRuntimeCrudExecution(requirement, caseId);
  if (runtimeCrud) return runtimeCrud;
  const actionCandidate = selectedActions.map((item) => catalog.actions[item.actionTemplateId]).find(Boolean);
  if (!actionCandidate?.step) return { setup: [], steps: [], cleanup: [], oracleBindings: [] };
  const primary = JSON.parse(JSON.stringify(actionCandidate.step)) as TestStep;
  const safeRequirement = requirement.requirement_id.replace(/[^A-Za-z0-9_.:-]+/g, "_");
  const responseName = "response_" + safeRequirement;
  if (primary.action === "api_request") primary.save_as = responseName;
  const setup: TestStep[] = [];
  const cleanup: TestStep[] = [];
  const steps: TestStep[] = [];
  const primaryApi = primary.action === "api_request" ? primary : undefined;
  const fixturePriority = priorityForFeature(catalog, requirement.feature_id);
  const collectionPath = primaryApi ? collectionPathFor(requirement, primaryApi) : "/";
  const setupResponse = "setup_" + safeRequirement;
  const setupSecondaryResponse = "setup_secondary_" + safeRequirement;
  const idPath = fixturePath(requirement, setupResponse, "read", primaryApi?.path || collectionPath);
  const needsItem = ["route_detail", "completed_state", "update_persists", "delete_removes_entity"].includes(requirement.intent);
  if (needsItem) {
    setup.push({ action: "api_request", method: "POST", path: collectionPath, body: fixtureBody(requirement, "AutoPW fixture", fixturePriority), save_as: setupResponse, acceptable_statuses: [201] });
    if (primaryApi) primaryApi.path = idPath;
    if (requirement.intent === "delete_removes_entity") cleanup.push({ action: "api_request", method: "GET", path: idPath, acceptable_statuses: [404] });
    else cleanup.push({ action: "api_request", method: "DELETE", path: fixturePath(requirement, setupResponse, "cleanup", idPath), acceptable_statuses: [204] });
  }
  if (requirement.intent === "create_succeeds") cleanup.push({ action: "api_request", method: "DELETE", path: fixturePath(requirement, responseName, "cleanup", `${collectionPath}/\${responses.${responseName}.body.id}`), acceptable_statuses: [204] });
  if (requirement.intent === "search_filters_results") {
    setup.push({ action: "api_request", method: "POST", path: collectionPath, body: fixtureBody(requirement, "AutoPW", fixturePriority), save_as: setupResponse, acceptable_statuses: [201] });
    setup.push({ action: "api_request", method: "POST", path: collectionPath, body: fixtureBody(requirement, "OtherPW", fixturePriority), save_as: setupSecondaryResponse, acceptable_statuses: [201] });
    cleanup.push({ action: "api_request", method: "DELETE", path: fixturePath(requirement, setupResponse, "cleanup", collectionPath), acceptable_statuses: [204] });
    cleanup.push({ action: "api_request", method: "DELETE", path: fixturePath(requirement, setupSecondaryResponse, "cleanup", collectionPath), acceptable_statuses: [204] });
  }
  const oracleBindings: string[] = [];
  const appendAssertion = (step: TestStep, bind = true): void => {
    if (bind) oracleBindings.push(`${caseId}:step_${setup.length + steps.length}`);
    steps.push(step);
  };
  steps.push(primary);
  if (requirement.intent === "create_succeeds") {
    const refreshName = "refresh_" + safeRequirement;
    steps.push({ action: "api_request", method: "GET", path: fixturePath(requirement, responseName, "read", collectionPath), save_as: refreshName });
  }
  if (requirement.intent === "count_consistent") steps.push({ action: "api_request", method: "GET", path: typeof requirement.oracle?.details?.collection_path === "string" ? requirement.oracle.details.collection_path : collectionPath, save_as: "list_" + safeRequirement });
  if (["completed_state", "update_persists"].includes(requirement.intent)) {
    const rereadName = "reread_" + safeRequirement;
    steps.push({ action: "api_request", method: "GET", path: idPath, save_as: rereadName });
  }
  const hasCandidateOracle = selectedExpectations.some((id) => Boolean(catalog.expectations[id]));
  const semanticRequired = ["create_succeeds", "update_persists", "summary_is_consistent", "count_consistent", "search_filters_results"].includes(requirement.intent);
  let semanticComplete = !semanticRequired;
  const expectedStatus = typeof requirement.oracle?.details?.status === "number" ? Number(requirement.oracle.details.status) : ["required_field_rejected", "enum_validation"].includes(requirement.intent) ? 400 : 200;
  appendAssertion({ action: "expect_status", source: `responses.${responseName}`, equals: expectedStatus }, !semanticRequired);
  if (requirement.intent === "create_succeeds" && !semanticRequired) appendAssertion({ action: "expect_json", source: `responses.${responseName}`, path: "id", exists: true });
  if (requirement.intent === "route_detail") appendAssertion({ action: "expect_json", source: `responses.${responseName}`, path: "id", exists: true });
  if (requirement.intent === "completed_state") appendAssertion({ action: "expect_json", source: `responses.reread_${safeRequirement}`, path: "completed", equals: true });
  if (requirement.intent === "delete_removes_entity") {
    const deleteReadback = "delete_readback_" + safeRequirement;
    steps.push({ action: "api_request", method: "GET", path: idPath, save_as: deleteReadback });
    appendAssertion({ action: "expect_status", source: `responses.${deleteReadback}`, equals: 404 });
  }
  if (requirement.oracle_specification?.proven !== false && requirement.intent === "create_succeeds") {
    const identity = requirement.fixture_strategy?.identity;
    const identityPath = identity?.path?.replace(/^body\./, "") || "id";
    if (identity?.kind === "location_header") appendAssertion({ action: "expect_relation", left: { source: `responses.refresh_${safeRequirement}`, path: "$response.status" }, operator: "equals", right: { literal: 200 } });
    else appendAssertion({ action: "expect_relation", left: { source: `responses.refresh_${safeRequirement}`, path: identityPath }, operator: "equals", right: { source: `responses.${responseName}`, path: identityPath } });
    semanticComplete = true;
  }
  if (requirement.oracle_specification?.proven !== false && requirement.intent === "update_persists") {
    const field = Object.keys(requirement.payload_strategy?.valid_payload || {})[0];
    if (field) { appendAssertion({ action: "expect_relation", left: { source: `responses.reread_${safeRequirement}`, path: field }, operator: "equals", right: { source: `responses.${responseName}`, path: field } }); semanticComplete = true; }
  }
  if (requirement.oracle_specification?.proven !== false && requirement.intent === "summary_is_consistent") {
    appendAssertion({ action: "expect_relation", left: { source: `responses.${responseName}`, path: "total" }, operator: "greater_or_equal", right: { source: `responses.${responseName}`, path: "completed" } });
    semanticComplete = true;
  }
  if (requirement.oracle_specification?.proven !== false && requirement.intent === "count_consistent") {
    appendAssertion({ action: "expect_relation", left: { source: `responses.${responseName}`, path: "count" }, operator: "equals", right: { source: `responses.list_${safeRequirement}`, aggregate: "length" } });
    semanticComplete = true;
  }
  if (requirement.oracle_specification?.proven !== false && requirement.intent === "search_filters_results") {
    const field = Object.keys(requirement.fixture_strategy?.payload || {}).find((key) => typeof requirement.fixture_strategy?.payload?.[key] === "string") || "title";
    appendAssertion({ action: "expect_collection", source: `responses.${responseName}`, quantifier: "every", predicate: { path: field, operator: "contains", value: "AutoPW" } });
    semanticComplete = true;
  }
  if (requirement.intent === "cors_allows_operation") appendAssertion({ action: "expect_header", source: `responses.${responseName}`, name: "access-control-allow-methods", contains: "PATCH" });
  return { setup, steps, cleanup, oracleBindings: hasCandidateOracle && semanticComplete ? oracleBindings : [] };
}

function buildRuntimeCrudExecution(requirement: RequirementLike, caseId: string): { setup: TestStep[]; steps: TestStep[]; cleanup: TestStep[]; oracleBindings: string[] } | undefined {
  if (!["create_succeeds", "update_persists", "delete_removes_entity"].includes(requirement.intent)) return undefined;
  const details = requirement.oracle?.details || {};
  const collectionPath = stringDetail(details, "collection_path", requirement.fixture_strategy?.create?.path || "/");
  const detailPath = stringDetail(details, "detail_path", requirement.fixture_strategy?.read?.path || collectionPath + "/:id");
  const createPath = stringDetail(details, "create_path", requirement.fixture_strategy?.create?.path || collectionPath);
  const updatePath = stringDetail(details, "update_path", requirement.fixture_strategy?.update?.path || detailPath);
  const deletePath = stringDetail(details, "delete_path", requirement.fixture_strategy?.cleanup?.path || detailPath);
  const safeId = safeRequirementId(requirement.requirement_id);
  const seed = "runtime_seed_" + safeId;
  const created = "runtime_created_" + safeId;
  const refreshed = "runtime_refreshed_" + safeId;
  const selected = "runtime_selected_" + safeId;
  const steps: TestStep[] = [];
  const cleanup: TestStep[] = [];
  const discoveredPayload = usableRuntimePayload(requirement.fixture_strategy?.payload) ? requirement.fixture_strategy?.payload : undefined;
  const cloneBody: Record<string, unknown> | string = discoveredPayload ? fixtureBody(requirement, "AutoPW generated", "normal") : `\${responses.${seed}.body.0}`;
  const expectedStatus = typeof details.status === "number" ? Number(details.status) : requirement.intent === "create_succeeds" ? 201 : requirement.intent === "delete_removes_entity" ? 204 : 200;

  steps.push({ action: "api_request", method: "GET", path: collectionPath, save_as: seed, acceptable_statuses: [200] });
  if (requirement.intent === "create_succeeds") {
    steps.push(
      { action: "api_request", method: "POST", path: createPath, body: cloneBody, save_as: created, acceptable_statuses: [expectedStatus] },
      { action: "api_request", method: "GET", path: collectionPath, save_as: refreshed, acceptable_statuses: [200] },
      { action: "expect_collection", source: `responses.${refreshed}`, quantifier: "some", predicate: { path: "id", operator: "equals", value: `\${responses.${created}.body.id}` } }
    );
    cleanup.push({ action: "api_request", method: "DELETE", path: fillIdentityPath(deletePath, `\${responses.${created}.body.id}`), acceptable_statuses: [204, 404] });
  } else if (requirement.intent === "update_persists") {
    const updated = "runtime_updated_" + safeId;
    if (discoveredPayload) steps.push({ action: "api_request", method: "POST", path: createPath, body: fixtureBody(requirement, "AutoPW fixture", "normal"), save_as: created, acceptable_statuses: [201] });
    const identitySource = discoveredPayload ? created : seed;
    const identityPath = discoveredPayload ? `\${responses.${identitySource}.body.id}` : `\${responses.${identitySource}.body.0.id}`;
    steps.push(
      { action: "api_request", method: requirement.fixture_strategy?.update?.method === "PUT" ? "PUT" : "PATCH", path: fillIdentityPath(updatePath, identityPath), body: discoveredPayload ? fixtureBody(requirement, "AutoPW updated", "normal") : cloneBody, save_as: updated, acceptable_statuses: [expectedStatus] },
      { action: "api_request", method: "GET", path: collectionPath, save_as: refreshed, acceptable_statuses: [200] },
      { action: "capture_json", source: `responses.${refreshed}`, path: `@id=\${responses.${updated}.body.id}`, save_as: selected },
      { action: "expect_relation", left: { source: `responses.${updated}` }, operator: "equals", right: { source: `variables.${selected}` } }
    );
    if (discoveredPayload) cleanup.push({ action: "api_request", method: "DELETE", path: fillIdentityPath(deletePath, `\${responses.${created}.body.id}`), acceptable_statuses: [204, 404] });
    else cleanup.push({ action: "api_request", method: requirement.fixture_strategy?.update?.method === "PUT" ? "PUT" : "PATCH", path: fillIdentityPath(updatePath, `\${responses.${seed}.body.0.id}`), body: cloneBody, acceptable_statuses: [200] });
  } else {
    steps.push(
      { action: "api_request", method: "POST", path: createPath, body: cloneBody, save_as: created, acceptable_statuses: [201] },
      { action: "api_request", method: "DELETE", path: fillIdentityPath(deletePath, `\${responses.${created}.body.id}`), save_as: "runtime_deleted_" + safeId, acceptable_statuses: [expectedStatus] },
      { action: "api_request", method: "GET", path: fillIdentityPath(detailPath, `\${responses.${created}.body.id}`), save_as: refreshed, acceptable_statuses: [404] },
      { action: "expect_status", source: `responses.${refreshed}`, equals: 404 }
    );
    cleanup.push({ action: "api_request", method: "GET", path: fillIdentityPath(detailPath, `\${responses.${created}.body.id}`), acceptable_statuses: [404] });
  }
  const oracleIndex = steps.findIndex((step) => step.action.startsWith("expect_"));
  return { setup: [], steps, cleanup, oracleBindings: oracleIndex >= 0 ? [`${caseId}:step_${oracleIndex}`] : [] };
}

function buildUiBehaviorExecution(requirement: RequirementLike, caseId: string): { setup: TestStep[]; steps: TestStep[]; cleanup: TestStep[]; oracleBindings: string[] } | undefined {
  if (!requirement.intent.startsWith("ui_")) return undefined;
  const details = requirement.oracle?.details || {};
  const route = stringDetail(details, "route", "/");
  const collectionPath = stringDetail(details, "collection_path", "/");
  const itemSelector = stringDetail(details, "item_selector");
  if (!itemSelector) return { setup: [], steps: [], cleanup: [], oracleBindings: [] };
  const setup: TestStep[] = [];
  const steps: TestStep[] = [];
  const cleanup: TestStep[] = [];
  const listResponse = "ui_list_" + safeRequirementId(requirement.requirement_id);
  const marker = "AutoPW-" + shortDigest(requirement.requirement_id).slice(0, 10);
  const item = discoveredLocator(itemSelector);
  const addOracle = (step: TestStep): void => { steps.push(step); };
  if (requirement.intent === "ui_count_consistent") {
    steps.push({ action: "api_request", method: "GET", path: collectionPath, save_as: listResponse, acceptable_statuses: [200] }, { action: "goto", path: route }, { action: "capture_count", locator: item, save_as: "rendered_count" }, { action: "capture_text", locator: discoveredLocator(stringDetail(details, "count_selector")), save_as: "displayed_count" });
    addOracle({ action: "expect_relation", left: { source: "variables.rendered_count" }, operator: "equals", right: { source: `responses.${listResponse}`, aggregate: "length" } });
    addOracle({ action: "expect_relation", left: { source: "variables.displayed_count", aggregate: "number" }, operator: "equals", right: { source: `responses.${listResponse}`, aggregate: "length" } });
  } else if (requirement.intent === "ui_search_filters") {
    const search = discoveredLocator(stringDetail(details, "search_selector"));
    steps.push({ action: "api_request", method: "GET", path: collectionPath, save_as: listResponse, acceptable_statuses: [200] }, { action: "goto", path: route }, { action: "fill", locator: search, value: `\${responses.${listResponse}.body.0.title}` }, { action: "wait_for", timeout_ms: 150 }, { action: "capture_texts", locator: item, save_as: "search_texts" });
    addOracle({ action: "expect_relation", left: { source: "variables.search_texts", aggregate: "length" }, operator: "greater_than", right: { literal: 0 } });
    addOracle({ action: "expect_collection", source: "variables.search_texts", quantifier: "every", predicate: { path: "", operator: "contains", value: `\${responses.${listResponse}.body.0.title}` } });
    steps.push({ action: "fill", locator: search, value: marker + "-missing" }, { action: "wait_for", timeout_ms: 100 }, { action: "capture_count", locator: item, save_as: "empty_search_count" });
    addOracle({ action: "expect_relation", left: { source: "variables.empty_search_count" }, operator: "equals", right: { literal: 0 } });
  } else if (requirement.intent === "ui_status_consistent") {
    steps.push({ action: "api_request", method: "GET", path: collectionPath, save_as: listResponse, acceptable_statuses: [200] }, { action: "goto", path: route }, { action: "capture_texts", locator: discoveredLocator(stringDetail(details, "status_selector")), save_as: "rendered_statuses" });
    if (Array.isArray(details.handled_values) && details.handled_values.length) addOracle({ action: "expect_collection", source: `responses.${listResponse}`, quantifier: "every", predicate: { path: stringDetail(details, "state_field", "status"), operator: "in", value: details.handled_values } });
    addOracle({ action: "expect_relation", left: { source: `responses.${listResponse}`, path: "[].status" }, operator: "same_partition", right: { source: "variables.rendered_statuses" } });
  } else if (requirement.intent === "ui_create_refreshes") {
    steps.push({ action: "goto", path: route }, { action: "fill", locator: discoveredLocator(stringDetail(details, "primary_input_selector"), numberDetail(details, "primary_input_nth")), value: marker });
    const secondary = stringDetail(details, "secondary_input_selector");
    if (secondary) steps.push({ action: "fill", locator: discoveredLocator(secondary, numberDetail(details, "secondary_input_nth")), value: "AutoPW generated description" });
    steps.push({ action: "click", locator: discoveredLocator(stringDetail(details, "submit_selector"), numberDetail(details, "submit_nth")) }, { action: "wait_for", timeout_ms: 150 });
    addOracle({ action: "expect_visible", locator: discoveredLocator(itemSelector, undefined, marker) });
    const cleanupList = "cleanup_created_list";
    cleanup.push({ action: "api_request", method: "GET", path: collectionPath, save_as: cleanupList, acceptable_statuses: [200] }, { action: "capture_json", source: `responses.${cleanupList}`, path: `@title=${marker}.id`, save_as: "created_id" }, { action: "api_request", method: "DELETE", path: fillIdentityPath(stringDetail(details, "delete_path", collectionPath + "/:id"), "${variables.created_id}"), acceptable_statuses: [204] });
  } else if (requirement.intent === "ui_toggle_refreshes") {
    const status = discoveredLocator(stringDetail(details, "status_selector"), 0);
    steps.push({ action: "api_request", method: "GET", path: collectionPath, save_as: listResponse, acceptable_statuses: [200] }, { action: "goto", path: route }, { action: "capture_text", locator: status, save_as: "status_before" }, { action: "click", locator: discoveredLocator(stringDetail(details, "toggle_selector"), 0, undefined, stringDetail(details, "toggle_scope_selector"), 0) }, { action: "wait_for", timeout_ms: 150 }, { action: "capture_text", locator: status, save_as: "status_after" });
    addOracle({ action: "expect_relation", left: { source: "variables.status_after" }, operator: "not_equals", right: { source: "variables.status_before" } });
    cleanup.push({ action: "api_request", method: (stringDetail(details, "update_path") ? "PATCH" : "PATCH"), path: fillIdentityPath(stringDetail(details, "update_path"), `\${responses.${listResponse}.body.0.id}`), acceptable_statuses: [200] });
  } else if (requirement.intent === "ui_delete_removes") {
    const fixtureResponse = "delete_fixture";
    setup.push({ action: "api_request", method: "GET", path: collectionPath, save_as: listResponse, acceptable_statuses: [200] }, { action: "api_request", method: "POST", path: stringDetail(details, "create_path", collectionPath), body: `\${responses.${listResponse}.body.0}`, save_as: fixtureResponse, acceptable_statuses: [201] });
    steps.push({ action: "goto", path: route }, { action: "capture_count", locator: item, save_as: "delete_count_before" }, { action: "click", locator: discoveredLocator(stringDetail(details, "delete_selector"), 0, undefined, stringDetail(details, "delete_scope_selector"), -1) }, { action: "wait_for", timeout_ms: 150 }, { action: "capture_count", locator: item, save_as: "delete_count_after" });
    addOracle({ action: "expect_relation", left: { source: "variables.delete_count_after" }, operator: "less_than", right: { source: "variables.delete_count_before" } });
    cleanup.push({ action: "api_request", method: "DELETE", path: fillIdentityPath(stringDetail(details, "delete_path"), `\${responses.${fixtureResponse}.body.id}`), acceptable_statuses: [204, 404] });
  }
  const oracleBindings = steps.map((step, index) => ({ step, index })).filter(({ step }) => step.action.startsWith("expect_")).map(({ index }) => `${caseId}:step_${setup.length + index}`);
  return { setup, steps, cleanup, oracleBindings };
}

function buildDetailConsistencyExecution(requirement: RequirementLike, caseId: string): { setup: TestStep[]; steps: TestStep[]; cleanup: TestStep[]; oracleBindings: string[] } {
  const details = requirement.oracle?.details || {};
  const collectionPath = stringDetail(details, "collection_path", "/");
  const detailPath = stringDetail(details, "detail_path", requirement.fixture_strategy?.read?.path || collectionPath + "/:id");
  const listName = "detail_collection_" + safeRequirementId(requirement.requirement_id);
  const detailName = "detail_response_" + safeRequirementId(requirement.requirement_id);
  const setup: TestStep[] = [];
  const cleanup: TestStep[] = [];
  const fixtureName = "detail_fixture_" + safeRequirementId(requirement.requirement_id);
  const selectedName = "detail_selected_" + safeRequirementId(requirement.requirement_id);
  const payload = usableRuntimePayload(requirement.fixture_strategy?.payload) ? requirement.fixture_strategy?.payload : undefined;
  if (payload && requirement.fixture_strategy?.create?.path) setup.push({ action: "api_request", method: "POST", path: requirement.fixture_strategy.create.path, body: fixtureBody(requirement, "AutoPW detail", "normal"), save_as: fixtureName, acceptable_statuses: [201] });
  const selectedIdentity = payload ? `\${responses.${fixtureName}.body.id}` : `\${responses.${listName}.body.1.id}`;
  const steps: TestStep[] = [{ action: "api_request", method: "GET", path: collectionPath, save_as: listName, acceptable_statuses: [200] }];
  if (payload) steps.push({ action: "capture_json", source: `responses.${listName}`, path: `@id=${selectedIdentity}`, save_as: selectedName });
  steps.push(
    { action: "api_request", method: "GET", path: fillIdentityPath(detailPath, selectedIdentity), save_as: detailName, acceptable_statuses: [200] },
    { action: "expect_relation", left: { source: `responses.${detailName}` }, operator: "equals", right: payload ? { source: `variables.${selectedName}` } : { source: `responses.${listName}`, path: "[1]" } }
  );
  if (payload && requirement.fixture_strategy?.cleanup?.path) cleanup.push({ action: "api_request", method: "DELETE", path: fillIdentityPath(requirement.fixture_strategy.cleanup.path, `\${responses.${fixtureName}.body.id}`), acceptable_statuses: [204, 404] });
  const oracleIndex = setup.length + steps.findIndex((step) => step.action === "expect_relation");
  return { setup, steps, cleanup, oracleBindings: [`${caseId}:step_${oracleIndex}`] };
}

function discoveredLocator(selector: string, nth?: number, hasText?: string, withinSelector?: string, withinNth?: number): import("@autopw/test-plan").LocatorRef {
  return { by: "css", value: selector, authority: "discovered_dom", ...(nth !== undefined ? { nth } : {}), ...(hasText !== undefined ? { has_text: hasText } : {}), ...(withinSelector ? { within: { by: "css", value: withinSelector, authority: "discovered_dom", ...(withinNth !== undefined ? { nth: withinNth } : {}) } } : {}) };
}
function usableRuntimePayload(payload: Record<string, unknown> | undefined): boolean {
  if (!payload) return false;
  const metadata = /^(?:id|.*_id|.*Id|priority|status|state|type|kind|createdAt|updatedAt)$/i;
  return Object.entries(payload).some(([key, value]) => !metadata.test(key) && (typeof value === "string" ? value.trim().length > 0 : typeof value === "number" || typeof value === "boolean"));
}
function stringDetail(details: Record<string, unknown>, name: string, fallback = ""): string { return typeof details[name] === "string" ? String(details[name]) : fallback; }
function numberDetail(details: Record<string, unknown>, name: string): number | undefined { return typeof details[name] === "number" ? Number(details[name]) : undefined; }
function fillIdentityPath(value: string, identity: string): string { return value.replace(/:[A-Za-z0-9_]+/, identity); }
function safeRequirementId(value: string): string { return value.replace(/[^A-Za-z0-9_.:-]+/g, "_"); }

function collectionPathFor(requirement: RequirementLike, primary: Extract<TestStep, { action: "api_request" }>): string {
  const fixtureCreate = requirement.fixture_strategy?.create?.path;
  if (fixtureCreate) return String(fixtureCreate).split("?")[0] || "/";
  const primaryPath = String(primary.path).split("?")[0];
  if (primary.method === "POST" && !primaryPath.includes(":id") && !primaryPath.includes("${")) return primaryPath || "/";
  return primaryPath || "/";
}
function fixturePath(requirement: RequirementLike, responseName: string, role: "read" | "update" | "cleanup", fallback: string): string {
  const fixture = requirement.fixture_strategy;
  const target = fixture?.[role]?.path || fallback;
  const identity = fixture?.identity;
  if (identity?.kind === "location_header") return `\${responses.${responseName}.headers.${identity.header || "location"}}`;
  if (identity?.kind === "explicit" && identity.path) return replacePathIdentity(target, identity.path);
  if (identity?.kind === "response_body" && identity.path) return replacePathIdentity(target, `\${responses.${responseName}.body.${identity.path.replace(/^body\./, "")}}`);
  return target;
}
function replacePathIdentity(path: string, identity: string): string { return path.replace(/:[A-Za-z0-9_]+/, identity); }
function fixtureBody(requirement: RequirementLike, marker: string, fallbackPriority: string): Record<string, unknown> { const base = { ...(requirement.fixture_strategy?.payload || {}) }; const stringField = Object.keys(base).find((key) => typeof base[key] === "string"); if (stringField) base[stringField] = marker; return Object.keys(base).length ? base : { title: marker, priority: fallbackPriority }; }
function tierForRequirement(requirement: RequirementLike): "smoke" | "fast" | "full" {
  if (requirement.priority === "P2") return "full";
  if (requirement.priority === "P1") return "fast";
  return ["invalid_input", "empty_state", "boundary"].includes(requirement.scenario) ? "fast" : "smoke";
}
const UI_ACTIONS = new Set<TestStep["action"]>(["goto", "reload", "fill", "click", "select", "check", "uncheck", "press", "wait_for"]);
function priorityForFeature(catalog: CandidateCatalog, featureId: string): string {
  for (const action of Object.values(catalog.actions)) {
    if (action.feature_id !== featureId || !action.step || typeof action.step.body !== "object" || action.step.body === null) continue;
    const priority = (action.step.body as Record<string, unknown>).priority;
    if (typeof priority === "string" && priority !== "unsupported") return priority;
  }
  return "normal";
}

export function assertSafeGeneratedSource(source: string): void {
  if (/(?:node:|child_process|\brequire\s*\(|import\s+.*from\s+['"]playwright)/i.test(source)) throw new Error("GENERATED_SUITE_FORBIDDEN_IMPORT");
}

export function suiteDigest(source: string): string { return crypto.createHash("sha256").update(source).digest("hex"); }
function requirementCaseId(requirementId: string): string { return "case_" + requirementId.replace(/[^A-Za-z0-9_.:-]+/g, "_"); }
function validScenario(value: string): TestPlan["cases"][number]["scenario"] { return (["normal", "required_field", "invalid_input", "empty_state", "boundary", "service_error", "network_failure", "not_found", "persistence", "cors"] as string[]).includes(value) ? value as TestPlan["cases"][number]["scenario"] : "normal"; }
function shortDigest(value: string): string { return crypto.createHash("sha256").update(value).digest("hex").slice(0, 16); }
function stableJson(value: unknown): string { if (Array.isArray(value)) return "[" + value.map(stableJson).join(",") + "]"; if (value && typeof value === "object") return "{" + Object.entries(value as Record<string, unknown>).sort(([a], [b]) => a.localeCompare(b)).map(([key, item]) => JSON.stringify(key) + ":" + stableJson(item)).join(",") + "}"; return JSON.stringify(value); }
function sortRecord(value: Record<string, string[]>): Record<string, string[]> { return Object.fromEntries(Object.entries(value).sort(([a], [b]) => a.localeCompare(b)).map(([key, items]) => [key, [...items].sort()])); }
function dedupeUnmapped(items: { requirement_id: string; reason: string }[]): { requirement_id: string; reason: string }[] { return [...new Map(items.map((item) => [item.requirement_id, item])).values()].sort((a, b) => a.requirement_id.localeCompare(b.requirement_id)); }
