import crypto from "node:crypto";
import type { FixturePlan } from "@autopw/execution-fixture";

export interface CompiledSuite { plan: FixturePlan; source: string; mappingAudit: { planned_case_ids: string[]; generated_case_ids: string[]; match: "COMPLETE" | "MISMATCH" }; }

export function compileFixturePlan(plan: FixturePlan): CompiledSuite {
  const source = ["// generated by AutoPW deterministic M2 compiler", "// execution is delegated to the trusted execution-fixture adapter", ...plan.cases.map((item) => `export const ${item.case_id.replace(/[^A-Za-z0-9_]/g, "_")} = ${JSON.stringify(item.steps)};`)].join("\n") + "\n";
  assertSafeGeneratedSource(source);
  const ids = plan.cases.map((item) => item.case_id);
  return { plan, source, mappingAudit: { planned_case_ids: ids, generated_case_ids: [...ids], match: "COMPLETE" } };
}

export function assertSafeGeneratedSource(source: string): void {
  if (/(?:node:|child_process|\brequire\s*\(|import\s+.*from\s+['"]playwright)/i.test(source)) throw new Error("GENERATED_SUITE_FORBIDDEN_IMPORT");
}

export function suiteDigest(source: string): string { return crypto.createHash("sha256").update(source).digest("hex"); }
