// Generate TypeScript enum/union types from the single-source enums.mjs so the
// "same enum across docs, Schema and generated types" invariant is mechanical:
// verify:m0 diffs the literals in enums.ts against enums.mjs.
import fs from "node:fs";
import path from "node:path";
import { ENUMS, ENUM_KEYS } from "../packages/schemas/src/enums.mjs";
import { LIMITS } from "../packages/schemas/src/limits.mjs";

const root = path.resolve(import.meta.dirname, "..");
const typesDir = path.join(root, "packages", "mcp-contracts", "src", "types");
fs.mkdirSync(typesDir, { recursive: true });

function union(arr) { return arr.map((v) => JSON.stringify(v)).join(" | "); }
function constArr(arr) { return "  [" + arr.map((v) => JSON.stringify(v)).join(", ") + "] as const"; }

let enums = "// GENERATED by tools/gen-types.mjs from packages/schemas/src/enums.mjs.\n";
enums += "// Do not edit by hand; verify:m0 diffs these literals against the enums module.\n\n";
for (const key of ENUM_KEYS) {
  const arr = ENUMS[key];
  const pascal = key.replace(/_([a-z])/g, (_, c) => c.toUpperCase()).replace(/^([a-z])/, (c) => c.toUpperCase());
  enums += "export const " + key + " = " + constArr(arr) + ";\n";
  enums += "export type " + pascal + " = typeof " + key + "[number];\n\n";
}

// limits -> const object + types
enums += "export const LIMITS = " + JSON.stringify(LIMITS, null, 2) + " as const;\n";
enums += "export type Limits = typeof LIMITS;\n\n";

fs.writeFileSync(path.join(typesDir, "enums.ts"), enums, "utf8");

// index.ts barrel
let idx = "// AutoPW MCP contracts type barrel (generated).\n";
idx += "export * from \"./enums\";\n";
fs.writeFileSync(path.join(typesDir, "index.ts"), idx, "utf8");

console.log("gen-types done: enums.ts written, enums:", ENUM_KEYS.length);
